### ISSUE TITLE
Discover stories based on location and distance

### ISSUE THREAD

**Issue by jessemoreburritos** [kennib/heritage-near-me#13]
- [x] Update database schema #31 
- [x] Get data from HOD #32 
- [ ] Access user location from browser

**Comment by kennib** [comment]
According to this [postgrest issue](https://github.com/begriffs/postgrest/issues/223) the best way to make this API work is using [stored procedures](http://postgrest.com/api/reading/#stored-procedures).

**Comment by nicklasaven** [comment]
Hi

I am a PostGIS guy that have resently found PostgREST. I find it very interesting.
I have done some testing, using the rpc approach to get data that intersects or is in a distance of.

If works great, but the result is not configurable as other output. 

So, maybe adding the same filter and select capabilities to the output of a rpc query is the easiest way.

But I also see in the doc that:
"Filters may be applied to computed columns as well as actual table/view columns, even though the computed columns will not appear in the output."

I don't understand fully how to read this. If it means that I can put ST_Interscts(geomA, geomB) in the select part and filter from that it would be great. I haven't succeeded though to do that, and it might result in that index doesn't kick in as expected, depending on how the resulting query against the db would look.

I have never written a line of Haskell, but maybe with some guidance I can take a look.

I have also a need to get binary data (twkb) (not base64) out of the database, but that is a later new issue, if there is any openings for doing such things.

**Comment by nicklasaven** [comment]
Ah sorry, maybe this was the wrong place for this. I followed a link and missed that i wasn't still in PostgREST  :-)
